type = "about"
title = "About"

[profile]
research_interests = [
  "Information Science / Social Computing",
  "Human-Centered AI",
  "Public Policy / Science and Technology Policy",
  "Visual Analytics",
  "Computational Social Science",
  "Graph Machine Learning"
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "About"

# [[sections]]
# id = "featured_publications"
# type = "publications"
# title = "Publications"
# filter = "selected"
# limit = 5
