[site]
title = "Han Wu"
description = "Undergraduate student at the University of Minnesota."
favicon = "/favicon.svg"
last_updated = "July 22,2026"

[author]
name = "Han Wu"
title = "Undergraduate Senior Student, Incoming graduate student"
institution = "University of Minnesota, University of Michigan"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "harveyng0507@gmail.com"
location = "Minneapolis, USA"

location_url = "https://www.google.com/maps/search/?api=1&query=55455"

location_details = [
  "Minneapolis, USA"
]


#google_scholar = "https://scholar.google.com"
#orcid = "https://orcid.org"
github = "https://github.com/hanwu-jet"
linkedin = "https://www.linkedin.com/in/harvey-wu-280822297/"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Experience"
type = "page"
target = "experience"
href = "/experience"


[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"


[[navigation]]
title = "Life"
type = "page"
target = "life"
href = "/life"

[[navigation]]
title = "News"
type = "page"
target = "news"
href = "/news"


[[navigation]]
title = "CV"
href = "/HanWu_Resume.pdf"
target = "cv"
type = "page"