type = "card"
title = "Life"
description = "My Cherished Moments"

[[items]]
title = "Example life"
subtitle = "Organization"
date = "2025"
content = "Description of the life."

#[[items]]
#title = "Example life"
#subtitle = "Organization"
#date = "2024"
#content = "Description of the life."

#[[items]]
#title = "2nd place in East China Division, EY ESG Youth Innovation Challenge"
#subtitle = "Ernst & Young China"
#date = "2023"
#content = "Description of the life."

#[[items]]
#title = "Champion of the XJTLU School Cup Football Tournament"
#subtitle = "Xi'an Jiaotong-Liverpool University"
#date = "2023"
#content = "Played as a defender and won the championship in a competition featuring eight teams."
