type = "about"
title = "关于我"

[profile]
research_interests = [
  "机器学习",
  "以人为本的人工智能",
  "多模态生成式人工智能",
  "人机交互与无障碍人工智能系统"
  
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "关于我"

# [[sections]]
# id = "featured_publications"
# type = "publications"
# title = "精选论文"
# filter = "selected"
# limit = 5
