[site]
title = "吴晗"
description = "吴晗个人主页。"
last_updated = "2026年7月22日"

[author]
name = "吴晗"
title = "本科大四生，即将攻读硕士"
institution = "明尼苏达大学，密歇根大学"


[[navigation]]
title = "关于我"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "发表"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "生活"
type = "page"
target = "life"
href = "/life"

[[navigation]]
title = "动态"
type = "page"
target = "news"
href = "/news"

[[navigation]]
title = "简历"
href = "/HanWu_Resume.pdf"
target = "cv"
type = "page"