type = "card"
title = "生活"
#description = "我的珍藏瞬间"

[[items]]
title = "示例"
subtitle = "机构"
date = "2025"
content = "说明"

#[[items]]
#title = "示例奖项"
#subtitle = "颁发机构"
#date = "2024"
#content = "奖项说明。"

#[[items]]
#title = "安永ESG青年创新挑战赛华东赛区亚军"
#subtitle = "安永中国"
#date = "2023"
#content = "奖项说明。"

#[[items]]
#title = "西交利物浦大学学院杯足球赛冠军"
#subtitle = "西交利物浦大学"
#date = "2023"
#content = "担当后卫，在8个队伍的角逐中取得冠军"
